stages:
  - build
  - test
  - deploy

image: python:latest

build-i686:
  image: quay.io/pypa/manylinux1_i686
  stage: build
  script: /opt/python/cp35-cp35m/bin/python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist

build-x86-64:
  image: quay.io/pypa/manylinux1_x86_64
  stage: build
  script: /opt/python/cp35-cp35m/bin/python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist

.test: &test
  stage: test
  script:
    - 'python -m pip install dist/syzoj_tools-*-py3-none-manylinux1_x86_64.whl'
    - 'syzoj --path=examples/a_plus_b test'
    - 'syzoj --path=examples/loj2 test'
test-3.7:
  <<: *test
  image: python:3.7
test-3.6:
  <<: *test
  image: python:3.6
test-3.5:
  <<: *test
  image: python:3.5

deploy-pypi:
  stage: deploy
  environment:
    name: pypi
  only:
    - master
  when: manual
  script:
    - 'python3 -m pip install --upgrade twine'
    - 'echo "[server-login]" >> $HOME/.pypirc'
    - 'echo "username: $PYPI_USERNAME" >> $HOME/.pypirc'
    - 'echo "password: $PYPI_PASSWORD" >> $HOME/.pypirc'
    - 'twine upload dist/*'
