stages:
  - build
  - test
  - deploy

image: python:latest

build:
  stage: build
  script: python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
      - build
      - dist

.test: &test
  stage: test
  script:
    - 'python -m pip install dist/*.whl'
    - 'syzoj --path=examples/a_plus_b test'
    - 'syzoj --path=examples/loj2'
test-3.7:
  <<: *test
  image: python:3.7
test-3.6:
  <<: *test
  image: python:3.6
test-3.5:
  <<: *test
  image: python:3.5
test-3.4:
  <<: *test
  image: python:3.4

deploy-pypi:
  stage: deploy
  environment:
    name: pypi
  only:
    - master
  when: manual
  script:
    - 'python3 -m pip install --upgrade twine'
    - 'echo "[server-login]" >> $HOME/.pypirc'
    - 'echo "username: $PYPI_USERNAME" >> $HOME/.pypirc'
    - 'echo "password: $PYPI_PASSWORD" >> $HOME/.pypirc'
    - 'twine upload dist/*'
